#pragma once

using namespace ATL;

template <class T>
class CProxy_IFakeDOMDocumentEvents : public IConnectionPointImpl<T, &__uuidof( _IFakeDOMDocumentEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
